# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20160201_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilpricedaily',
            name='month',
            field=models.CharField(choices=[('E', 'Enero'), ('F', 'Febrero'), ('M', 'Marzo'), ('A', 'Abril'), ('M', 'Mayo'), ('J', 'Junio')], default='May', max_length=15),
            preserve_default=False,
        ),
    ]
