# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_oilpricedaily_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oilpricedaily',
            name='month',
            field=models.CharField(choices=[('EN', 'Enero'), ('FE', 'Febrero'), ('MA', 'Marzo'), ('AB', 'Abril'), ('MY', 'Mayo'), ('JU', 'Junio'), ('JL', 'Julio'), ('AG', 'Agosto'), ('SP', 'Septiembre'), ('OC', 'Octubre'), ('NV', 'Noviembre'), ('DC', 'Diciembre')], max_length=15),
        ),
    ]
